DROP TABLE IF EXISTS `pro_public`;
CREATE TABLE `pro_public` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键Id,逻辑id,软件内部关联;不要把此id暴露在前端;',
  `state` INT NOT NULL DEFAULT '1' COMMENT '-1:删除 | 0:停用 | 1:启用; 默认为 1',
  `classify_code` VARCHAR (20) DEFAULT '' COMMENT '产品分类表的code;默认'':无分类;',
  `name` VARCHAR (50) DEFAULT '' NULL COMMENT '品牌名称',
  `type_no` VARCHAR (50) DEFAULT '' NULL COMMENT '型号',
  `serial_no` VARCHAR (50) DEFAULT '' COMMENT '系列号',
  `watch_core_type` VARCHAR (50) DEFAULT '' NULL COMMENT '机芯类型',
  `watchcase` VARCHAR (50) DEFAULT '' COMMENT '表壳材质',
  `watchcase_size` VARCHAR (50) DEFAULT '' COMMENT  '表盘直径',
  `material` VARCHAR (100) DEFAULT '' COMMENT '材质',
  `object_size` VARCHAR (100) DEFAULT '' COMMENT '尺寸;一般有长宽高',
  `clothes_size` VARCHAR (100) DEFAULT '' COMMENT '尺码;一般指衣服和鞋的大小',
  `public_price` INT DEFAULT 0 COMMENT '国内公价(元)',
  `small_img` VARCHAR (255) DEFAULT '' COMMENT '公价图地址',
  `insert_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` TIMESTAMP NULL DEFAULT NULL COMMENT '修改时间',
  `insert_admin` INT DEFAULT NULL COMMENT '添加用户_管理员id',
  `update_admin` INT DEFAULT NULL COMMENT '修改用户_管理员id',
  `versions` INT NOT NULL DEFAULT 1 COMMENT '版本号;用于更新时对比操作;',
  `remark` VARCHAR (255) DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`),
  KEY `idx_state` (`state`) USING BTREE,
  KEY `idx_serial_no` (`serial_no`) USING BTREE,
  KEY `idx_type_no` (`type_no`) USING BTREE,
  KEY `fk_classify_code` (`classify_code`) USING BTREE,
  KEY `idx_name` (`name`) USING BTREE
) ENGINE = INNODB AUTO_INCREMENT = 100000 COMMENT = '公价商品表' ;
