#友商表添加来源字段 仅执行此操作
ALTER TABLE `biz_leaguer_add`
    ADD COLUMN `source`  varchar(20)  DEFAULT '0' COMMENT '友商来源' AFTER `state`;


DROP TABLE
IF EXISTS `pro_standard`;

CREATE TABLE `pro_standard` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键Id,逻辑id,软件内部关联;不要把此id暴露在前端;',
  `fk_pro_product_id`  int NOT NULL COMMENT '商品主键Id,逻辑id,软件内部关联;不要把此id暴露在前端;',
  `fk_shp_shop_id`  int NOT NULL COMMENT '店铺主键Id,逻辑id,软件内部关联;不要把此id暴露在前端;',
  `watch_core_type` varchar(500)  DEFAULT '' COMMENT '机芯类型',
  `watchcase` varchar(500)  DEFAULT '' COMMENT '表壳材质',
  `watchcase_size` varchar(500)  DEFAULT '' COMMENT '表盘直径',
  `material` varchar(500)  DEFAULT '' COMMENT '材质',
  `object_size` varchar(500)  DEFAULT '' COMMENT '尺寸;一般有长宽高',
  `clothes_size` varchar(500)  DEFAULT '' COMMENT '尺码;一般指衣服和鞋的大小',
  `public_price` varchar(100) DEFAULT '0' COMMENT '国内公价(元)',
  `insert_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '插入时间',
  `update_time` timestamp NULL DEFAULT NULL COMMENT '修改时间',
  `insert_admin` int NOT NULL COMMENT '新增用户_管理员id',
  `update_admin` int DEFAULT NULL COMMENT '修改用户_管理员id',
  `versions` int NOT NULL DEFAULT '1' COMMENT '版本号;用于更新时对比操作;',
  `del` varchar(1)  NOT NULL DEFAULT '0' COMMENT '是否逻辑删除;0:false:不删除;1:true:逻辑删除;对用户显示，所有查询sql都要带上del=0这个条件',
  `remark` varchar(500)  DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`id`) USING BTREE
) AUTO_INCREMENT=10000 COMMENT='商品规格表';

#在订单表新增结款人员、结款时间字段
ALTER TABLE `ord_order`
    ADD COLUMN `entrust_admin` int DEFAULT NULL COMMENT '结款人员' AFTER `deduct_voucher_img_url`;
ALTER TABLE `ord_order`
    ADD COLUMN `entrust_time`  timestamp NULL DEFAULT NULL COMMENT '结款时间' AFTER `entrust_admin`;

#新增补充信息内容
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10004', NULL, '机芯类型', '', '', 'WB', '-9', '10000', '2', '2', '1', '1', '2021-08-05 17:43:16', '2021-09-17 10:58:41', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10007', NULL, '表盘直径', '', '', 'WB', '-9', '10001', '2', '2', '1', '3', '2021-08-05 17:48:09', '2021-09-16 18:06:39', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10008', NULL, '尺寸', '', '', 'WB', '-9', '10001', '2', '2', '1', '5', '2021-08-05 17:48:30', '2021-09-16 18:11:55', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10009', NULL, '尺码', '', '', 'WB', '-9', '10001', '2', '2', '1', '6', '2021-08-05 17:48:41', '2021-09-16 18:12:17', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10013', NULL, '表壳材质', '', '', 'WB', '-9', '10002', '2', '2', '1', '2', '2021-08-05 17:49:55', '2021-09-17 10:58:44', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10016', NULL, '材质', '', '', 'WB', '-9', '10002', '2', '2', '1', '4', '2021-08-05 17:50:23', '2021-09-16 18:08:06', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10060', NULL, '尺寸', '', '', 'XB', '-9', '10025', '2', '2', '1', '2', '2021-08-06 20:26:08', '2021-08-13 15:17:39', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10063', NULL, '尺码', '', '', 'XB', '-9', '10025', '2', '2', '1', '3', '2021-08-06 20:29:45', '2021-09-16 18:22:27', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10064', NULL, '材质', '', '', 'XB', '-9', '10026', '2', '2', '1', '1', '2021-08-06 20:34:34', '2021-09-16 18:17:11', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10121', NULL, '材质', '', '', 'ZB', '-9', NULL, '2', '2', '1', '1', '2021-08-27 11:09:31', '2021-09-09 17:05:10', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10130', NULL, '尺码', '', '', 'ZB', '-9', NULL, '2', '2', '1', '3', '2021-09-09 17:05:24', '2021-09-16 18:15:20', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10131', NULL, '尺码', '', '', 'XX', '-9', NULL, '2', '2', '1', '3', '2021-09-09 17:07:20', '2021-09-16 19:22:48', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10132', NULL, '材质', '', '', 'PS', '-9', NULL, '2', '2', '1', '1', '2021-09-09 17:09:19', '2021-09-09 17:09:31', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10133', NULL, '尺码', '', '', 'FS', '-9', NULL, '2', '2', '1', '3', '2021-09-09 17:10:12', '2021-09-16 19:22:04', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10134', NULL, '尺寸', '', '', 'ZB', '-9', NULL, '2', '2', '1', '2', '2021-09-09 17:12:52', '2021-09-16 18:15:16', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10145', NULL, '材质', '', '', 'FS', '-9', NULL, '2', '2', '1', '1', '2021-09-09 17:25:54', '2021-09-09 17:26:13', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10146', NULL, '材质', '', '', 'XX', '-9', NULL, '2', '2', '1', '1', '2021-09-09 17:50:50', '2021-09-16 18:15:33', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10147', NULL, '材质', '', '', 'QT', '-9', NULL, '2', '2', '1', '1', '2021-09-09 17:59:34', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10148', NULL, '尺寸', '', '', 'QT', '-9', NULL, '2', '2', '1', '2', '2021-09-09 17:59:44', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10149', NULL, '尺码', '', '', 'QT', '-9', NULL, '2', '2', '1', '3', '2021-09-09 17:59:53', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10151', NULL, '尺寸', '', '', 'PS', '-9', NULL, '2', '2', '1', '2', '2021-09-09 18:03:02', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10152', NULL, '尺码', '', '', 'PS', '-9', NULL, '2', '2', '1', '3', '2021-09-09 18:03:18', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10153', NULL, '尺寸', '', '', 'FS', '-9', NULL, '2', '2', '1', '2', '2021-09-16 19:22:00', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10154', NULL, '尺寸', '', '', 'XX', '-9', NULL, '2', '2', '1', '2', '2021-09-16 19:22:43', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10155', NULL, '官方指导价', '', '', 'ZB', '-9', NULL, '2', '2', '1', '4', '2021-09-17 10:19:47', '2021-09-17 10:20:49', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10156', NULL, '官方指导价', '', '', 'XX', '-9', NULL, '2', '2', '1', '4', '2021-09-17 10:20:07', '2021-09-17 10:20:54', '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10157', NULL, '官方指导价', '', '', 'XB', '-9', NULL, '2', '2', '1', '4', '2021-09-17 10:20:40', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10158', NULL, '官方指导价', '', '', 'WB', '-9', NULL, '2', '2', '1', '7', '2021-09-17 10:21:10', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10159', NULL, '官方指导价', '', '', 'QT', '-9', NULL, '2', '2', '1', '4', '2021-09-17 10:21:29', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10160', NULL, '官方指导价', '', '', 'PS', '-9', NULL, '2', '2', '1', '4', '2021-09-17 10:21:43', NULL, '-9', NULL, '1', '0', '');
INSERT INTO `pro_classify_type` (`id`, `code`, `name`, `description`, `icon_url`, `fk_pro_classify_code`, `fk_shp_shop_id`, `pro_classify_type_id`, `type`, `chose_type`, `state`, `sort`, `insert_time`, `update_time`, `insert_admin`, `update_admin`, `versions`, `del`, `remark`) VALUES ('10161', NULL, '官方指导价', '', '', 'FS', '-9', NULL, '2', '2', '1', '4', '2021-09-17 10:32:30', '2021-09-17 20:04:16', '-9', NULL, '1', '0', '');
