#测试环境(外网测试环境)
# 数据源的配置信息
spring:
  datasource:
    url: jdbc:mysql://rm-bp10b1638kx24023s.mysql.rds.aliyuncs.com:3306/shedangjia-test?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: testuser
    password: Test123456
    #连接池的配置信息
    initialSize: 10
    minIdle: 10
    maxActive: 100
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  data:
    mongodb:
      uri: mongodb://root:Mongo_123@dds-bp16deb814f4e7941459-pub.mongodb.rds.aliyuncs.com:3717,dds-bp16deb814f4e7942558-pub.mongodb.rds.aliyuncs.com:3717/kuaketest?authSource=admin

  # Redis配置信息
  redis:
    # Redis数据库索引（默认为0）=0
    database: 5
    # Redis服务器地址=127.0.0.1
    #host: 127.0.0.1
    #host: 192.168.0.104
    #host: 192.168.0.105
    host: r-bp10lxpiz0p7gnk1q3.redis.rds.aliyuncs.com
    # Redis服务器连接端口=6379
    port: 6379
    # Redis服务器连接密码（默认为空）=123456
    password: Redis_123
    # 连接超时时间（毫秒）=1000
    timeout: 5000

myLog:
  level: debug
  path: /mnt/luxuryadmin-test-log

#阿里云OSS配置
#原服务器地址
oss:
  bucketUrl: https://luxuryadmin-test.oss-cn-hangzhou.aliyuncs.com
  #自定义解析后服务器地址
  domain: http://file-test.luxuryadmin.com
  #可以选择其他的地址
  endpoint: https://oss-cn-hangzhou.aliyuncs.com
  #已经在控制台创建的bucket
  bucketName: luxuryadmin-test
  #你上传文件的保存路径，如果bucket中不存在则创建（其实原理并不是文件夹，只是文件名，详情请先阅读官方文档）
  #picLocation: GitClub/image/
  #相应的id和key值，请填写你具体的值，这里不方便展示我自己的。
  accessKeyId: LTAI4FfBXq3pag9SNBRJHtSU
  accessKeySecret: QsfkNiz59wtoyHDFC9Gbq6ZWIJJQxM

#极光推送配置
jiguang:
  masterSecret: 065a3f9bfa4286422ded4d75
  appKey: 2076185b89aab000d4e958aa