#生产环境(线上真实环境)
# 数据源的配置信息
spring:
    datasource:
        url: jdbc:mysql://rm-bp10b1638kx24023s.mysql.rds.aliyuncs.com:3306/luxury?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: shedangjia_real
        password: shedangjia_123
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20

    # Redis配置信息
    redis:
        # Redis数据库索引（默认为0）=0
        #database: 0
        # Redis服务器地址=127.0.0.1
        #host: 127.0.0.1
        #host: 192.168.0.104
        #host: 192.168.0.105
        host: r-bp10lxpiz0p7gnk1q3.redis.rds.aliyuncs.com
        # Redis服务器连接端口=6379
        port: 6379
        # Redis服务器连接密码（默认为空）=123456
        password: Redis_123
        # 连接超时时间（毫秒）=1000
        timeout: 5000

#阿里云OSS配置
oss:
    bucketUrl: https://luxuryadmin.oss-cn-hangzhou.aliyuncs.com
    domain: https://file.luxuryadmin.com
    #生产环境用内网的endpoint
    endpoint: https://oss-cn-hangzhou-internal.aliyuncs.com
    #已经在控制台创建的bucket
    bucketName: luxuryadmin
    accessKeyId: LTAI4FfBXq3pag9SNBRJHtSU
    accessKeySecret: QsfkNiz59wtoyHDFC9Gbq6ZWIJJQxM

jiguang:
    masterSecret: 065a3f9bfa4286422ded4d75
    appKey: 2076185b89aab000d4e958aa

#linux环境
myLog:
    level: info
    path: /mnt/luxuryadmin-log

#公价查询连接 选取公价图的时候添加参数
public:
    url: https://www.luxuryadmin.com/h5/price-query.html?selectPublic=1

#商家联盟认证链接
union:
    url: https://www.luxuryadmin.com/h5/union-info-submit.html
