#开发环境
# 数据源的配置信息
spring:
    datasource:
        url: jdbc:mysql://192.168.0.249:3306/luxury?serverTimezone=Asia/Shanghai&allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 123456
        #连接池的配置信息

    # Redis配置信息
    redis:
        # Redis数据库索引（默认为0）=0
        #database: 0
        # Redis服务器地址=127.0.0.1
        #host: 127.0.0.1
        host: 192.168.0.249
        #公司虚拟机ip
        #host: 127.0.0.1
        # Redis服务器连接端口=6379
        port: 6379
        # Redis服务器连接密码（默认为空）=123456
        password: 123456
        # 连接超时时间（毫秒）=1000
        timeout: 5000

#阿里云OSS配置
oss:
    bucketUrl: https://luxuryadmin-test.oss-cn-hangzhou.aliyuncs.com
    domain: http://file-test.luxuryadmin.com
    #开发环境用外网的endpoint
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    #已经在控制台创建的bucket
    bucketName: luxuryadmin-test
    accessKeyId: LTAI4FfBXq3pag9SNBRJHtSU
    accessKeySecret: QsfkNiz59wtoyHDFC9Gbq6ZWIJJQxM


myLog:
    level: debug
    path: E:/luxuryadmin-log




#极光推送配置
jiguang:
    masterSecret: 065a3f9bfa4286422ded4d75
    appKey: 2076185b89aab000d4e958aa

